export const servicesConstants = {
  GET_SERVICES_REQUEST: 'GET_SERVICES_REQUEST',
  GET_SERVICES_SUCCESS: 'GET_SERVICES_SUCCESS',
  GET_SERVICES_FAILURE: 'GET_SERVICES_FAILURE',
  
  CREATE_SERVICE_REQUEST: 'CREATE_SERVICE_REQUEST',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_FAILURE: 'CREATE_SERVICE_FAILURE',

  UPDATE_SERVICE_REQUEST: 'UPDATE_SERVICE_REQUEST',
  UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
  UPDATE_SERVICE_FAILURE: 'UPDATE_SERVICE_FAILURE',

  DELETE_SERVICE_REQUEST: 'DELETE_SERVICE_REQUEST',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
  DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',
};